import Head from "next/head";
import {
  Container,
  Row,
  Col,
  Navbar,
  Nav,
  Button,
  NavDropdown,
} from "react-bootstrap";
import Image from "next/image";
//import logo from "../../public/images/logo.png";
import "bootstrap/dist/css/bootstrap.css";

export default function Header() {
  const handleChange = () => {
    window.location.href = 'https://job-qna.herokuapp.com/v1/auth/linkedin'
  }
  return (
    <>
      <Head>
        <title>Autojob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://apis.google.com/js/platform.js" async defer></script>
        <meta name="google-signin-client_id" content="451960284760-ir1p0vi132hgttgj9ejdos6l0gnj727l.apps.googleusercontent.com" />
        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <div id="g_id_onload"
          data-client_id="451960284760-ir1p0vi132hgttgj9ejdos6l0gnj727l.apps.googleusercontent.com"
          data-login_uri="http://localhost:3000/v1/auth/google"
          data-auto_prompt="true">
        </div> */}

      </Head>

      <Navbar bg="light" expand="lg" fixed="top">
        <Container>
          <Navbar.Brand href="/">
          <h2>AUTOJOB</h2>
            {/* <img src="/img/logo.png" alt="Spaceshift" /> */}
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav" className="navBarTop">
            <Nav className="me-auto">
              <Nav.Link href="/">Home</Nav.Link>
             
              <Nav.Link href="#home">About Us</Nav.Link>
              <Nav.Link href="/quesPost">Posts</Nav.Link>
              <Nav.Link href="/jobs">Jobs</Nav.Link>
              <Nav.Link href="/referralJob">Refer a Job</Nav.Link>
              <Nav.Link href="/contactus">Contact Us</Nav.Link>
              <Nav.Link><button class="btn btn-linkedin btn-lg" onClick={handleChange}><i class="fa fa-linkedin fa-fw"></i> LinkedIn</button></Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </>
  );
}
